#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

counter=0

helm upgrade --install nyws "$SCRIPTPATH/manifests/workshop-global" -f values-glob.yaml

lb="$(cat $SCRIPTPATH/values-glob.yaml | yq ".host")"
ssh_node="$(cat $SCRIPTPATH/values-glob.yaml | yq ".host")"
start_port="$(cat $SCRIPTPATH/values-glob.yaml | yq ".startPort")"

echo "$ssh_node"
echo "$NLB_EP"

for i in $(cat $SCRIPTPATH/manifests/workshop-global/users.txt)
do
  user="${i}"
  user_port=$(( start_port + counter ))
  export LC_ALL=C
  password="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')"
  
  helm upgrade --install nyws-user-${user} $SCRIPTPATH/manifests/workshop-global -f values-user.yaml --set "user.name=${user}" --set "user.password=${password}" --set "user.port=${user_port}"

  mkdir -p "$SCRIPTPATH/manifests/configs"

  echo "ssh -o ServerAliveInterval=60 -p ${user_port} admin@${NLB_EP}" > "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "user: admin, password: ${password}, namespace: ${user}" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "AWS endpoint: ${lb}" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "-----------------------------------------------------------" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo -e "Docker registry: \n\nuser: AWS, \n\npassword: $(cat $SCRIPTPATH/tmp_ecr_cred), \n\nimage name: $(cat $SCRIPTPATH/tmp_ecr)" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "-----------------------------------------------------------" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "Runbook Part I: https://github.com/skabrits/Kubernetes-workshop/blob/master/documentation/Part%20I/README.md" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "Runbook Part II: https://github.com/skabrits/Kubernetes-workshop/blob/master/documentation/Part%20II/README.md" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "Demos Part I: https://github.com/skabrits/Kubernetes-workshop/tree/master/demo/Part%20I" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"
  echo "Demos Part II: https://github.com/skabrits/Kubernetes-workshop/tree/master/demo/Part%20II" >> "$SCRIPTPATH/manifests/configs/creds-${user}.txt"

  counter=$((counter + 1))
done
