apiVersion: apps/v1
kind: Deployment
metadata:
  name: workhorse
  namespace: {username}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workhorse
  template:
    metadata:
      labels:
        app: workhorse
    spec:
      containers:
      - name: workhorse
        image: skabrits/workhorse
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: workhorse-svc
  namespace: {username}
spec:
  selector:
    app: workhorse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 22
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workhorse-ing
  namespace: {username}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{username}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: workhorse-svc
            port:
              number: 80