apiVersion: apps/v1
kind: Deployment
metadata:
  name: checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checker
  template:
    metadata:
      labels:
        app: checker
    spec:
      containers:
      - name: checker
        image: skabrits/checker:0.1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: "config"
          mountPath: /app/endpoint.txt
          subpath: endpoint.txt
        - name: "config"
          mountPath: /app/names.txt
          subpath: names.txt
      serviceAccountName: checker-sa
      volumes:
      - name: "config"
        configMap:
          name: "checker-config-cm"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checker-config-cm
data:
{{ (.Files.Glob "**.txt").AsConfig | indent 2 }}
  endpoint.txt: |-
    {{ .Values.host }}
---
apiVersion: v1
kind: Service
metadata:
  name: checker-svc
spec:
  selector:
    app: checker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checker-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-cluster
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /results(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: checker-svc
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: kubeflow-checker-cert