{{- $startPort := .Values.startPort -}}
{{- $basenamespace := .Values.basenamespace -}}
{{- $svcPort := .Values.svcPort -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  {{- range $i, $value := (.Files.Lines "users.txt") }}
  {{ add $startPort $i }}: "{{ $basenamespace }}/workhorse-svc-{{ $value }}:{{ $svcPort }}"
  {{- end }}
  