{{- $startPort := .Values.startPort -}}
{{- $basenamespace := .Values.basenamespace -}}
{{- $podPort := .Values.podPort -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  {{- range $i, $value := (.Files.Lines "users.txt") }}
  {{ add $startPort $i }}: "{{ $basenamespace }}/workhorse-svc-{{ $value }}:{{ $podPort }}"
  {{- end }}
  